# Generated by Django 4.2.16 on 2024-11-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('love', '❤️ Love'), ('like', '👍 Like'), ('haha', '😂 Haha'), ('wow', '😮 Wow'), ('crying', '😭 Crying'), ('angry', '😡 Angry')], max_length=20),
        ),
    ]
