# Generated by Django 4.2.16 on 2024-11-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0006_alter_reaction_reaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('love', 'Love'), ('like', ' Like'), ('haha', ' Haha'), ('wow', ' Wow'), ('crying', ' Crying'), ('angry', ' Angry'), ('remove', 'Remove')], max_length=10),
        ),
    ]
