# Generated by Django 4.2.16 on 2024-11-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_follow_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background_pic',
        ),
    ]
